# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtriggers', '0006_auto_20171003_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='successful',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
